spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://pharmacy-recommendation-database:3306/pharmacyRecommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: pharmacy-recommendation-redis
    port: 6379

pharmacy:
  recommendation:
    base:
      url: http://localhost/dir/

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}