spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 9836
    url: jdbc:mariadb://localhost:3306/FindingShelter

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}
